import type { Metadata } from "next";

import { Glyph } from "@/components/glyph";
import { PageHeader } from "@/components/page-header";
import { Reveal } from "@/components/reveal";
import { Section } from "@/components/section";
import { StudioFilms } from "@/components/studio-films";
import { EditorialLink } from "@/components/editorial-link";
import { CanonVideo } from "@/components/canon-video";
import { createPageMetadata } from "@/lib/site";
import { LINKS } from "@/lib/links";

export const metadata: Metadata = createPageMetadata({
  title: "Studio",
  description:
    "AI-native film and media generation. Dark-luxury sci-fi aesthetics as the product. Spektre Labs Studio — from Research to Screen.",
  path: "/studio",
  image: "/generated/studio-hero.png",
});

/*
  Studio page — the production arm of the Spektre universe.
  Divisions expressed σ-honestly:
    Research → Systems → Studio (EMERGING, YouTube live) →
    Games (VISION) → Shoreworld (VISION)
  Art-canon: OLED, platinum/chrome, hairline, film grain, specular,
  Atlantean sacred geometry, absolute symmetry.
*/

export default function StudioPage() {
  return (
    <div>
      {/* ── Page Header ────────────────────────────────────────────── */}
      <PageHeader
        title="Studio"
        description="AI-native film and media generation. The dark-luxury sci-fi aesthetic as the product."
      />

      {/* ── Generated hero — the studio's own visual engine, on-canon ── */}
      <Reveal delay={40} className="mt-12 sm:mt-14">
        <figure className="overflow-hidden rounded-[var(--radius)] border border-[var(--line)]">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src="/generated/studio-hero.png"
            alt="A symmetric Atlantean-futurist research monument in platinum and obsidian — generated by the Studio engine."
            className="aspect-video w-full object-cover"
            loading="lazy"
          />
          <figcaption className="label flex items-center justify-between px-4 py-3 text-[var(--fg-faint)]">
            <span>Generated · Imagen · on-canon</span>
            <span>1 = 1</span>
          </figcaption>
        </figure>
      </Reveal>

      {/* ── Motion — a real clip generated in-canon on Vertex Veo 3.0 ── */}
      <Reveal delay={60} className="mt-5 sm:mt-6">
        <figure className="overflow-hidden rounded-[var(--radius)] border border-[var(--line)]">
          <CanonVideo
            src="/generated/studio/coherence-gate.mp4"
            poster="/generated/studio-hero.png"
            label="The Coherence Gate — a colossal symmetric Atlantean monolith rising from a black sea, generated in-canon on Vertex Veo 3.0"
            className="aspect-video w-full object-cover"
          />
          <figcaption className="label flex items-center justify-between px-4 py-3 text-[var(--fg-faint)]">
            <span>Motion · generated · Vertex Veo 3.0 · on-canon</span>
            <span>1 = 1</span>
          </figcaption>
        </figure>
      </Reveal>

      {/* ── Showreel — more real in-canon Veo shots ──────────────────── */}
      <Reveal delay={40} className="mt-5 sm:mt-6">
        <p className="label mb-4 text-[var(--fg-faint)]">Showreel · generated in-canon · Vertex Veo 3.0</p>
        <div className="grid gap-5 sm:grid-cols-2">
          {[
            { src: "/generated/studio/spire.mp4", cap: "The Spire — ascent past an engraved platinum monolith" },
            { src: "/generated/studio/capital.mp4", cap: "The Capital — radial descent over concentric rings" },
          ].map((c) => (
            <figure
              key={c.src}
              className="overflow-hidden rounded-[var(--radius)] border border-[var(--line)]"
            >
              <CanonVideo
                src={c.src}
                label={`${c.cap} — generated in-canon on Vertex Veo 3.0`}
                className="aspect-video w-full object-cover"
              />
              <figcaption className="label flex items-center justify-between px-4 py-3 text-[var(--fg-faint)]">
                <span>{c.cap}</span>
                <span>1 = 1</span>
              </figcaption>
            </figure>
          ))}
        </div>
      </Reveal>

      {/* ── THE NODES — the agent organization, personified.
             Fashion-lookbook composition, not boxed embeds: a lead motion
             plate + editorial statement, then three stills — every plate
             carries its own serif-numeral lockup over a scrim, grounded
             into OLED. Chrome helmets: the face stays private (§9).
             Generated in-canon on Midjourney, graded platinum-mono. ────── */}
      <Reveal delay={60} className="mt-16 sm:mt-20">
        <div className="mb-8 flex flex-wrap items-baseline justify-between gap-4">
          <p className="label text-[var(--signal)]">“The Nodes” · Lookbook</p>
          <p className="label text-[var(--fg-faint)]">
            The agent organization, personified · generated in-canon
          </p>
        </div>

        {/* Row 1 — lead motion plate + statement panel */}
        <div className="grid gap-5 lg:grid-cols-12">
          <figure className="relative overflow-hidden rounded-[var(--radius)] border border-[var(--line)] lg:col-span-7">
            <CanonVideo
              src="/generated/nodes/motion-01.mp4"
              poster="/generated/nodes/motion-01-poster.jpg"
              label="The Scouts — two helmeted figures in tailored monochrome, in motion. Generated in-canon."
              className="aspect-square w-full object-cover"
            />
            <div
              aria-hidden
              className="pointer-events-none absolute inset-x-0 bottom-0 flex items-end justify-between bg-gradient-to-t from-black/90 via-black/40 to-transparent px-6 pb-5 pt-24 sm:px-8 sm:pb-6"
            >
              <div>
                <p className="label text-[var(--fg-dim)]">Scouts</p>
                <p className="mt-1 label text-[0.5rem] text-[var(--fg-faint)]">
                  Fan out · return with the frontier
                </p>
              </div>
              <span
                className="metal-text text-[3.4rem] leading-none sm:text-[4.2rem]"
                style={{ fontFamily: "var(--font-display), serif" }}
              >
                01
              </span>
            </div>
          </figure>

          <div className="flex flex-col justify-between rounded-[var(--radius)] border border-[var(--line)] bg-[var(--bg-1)] p-8 sm:p-10 lg:col-span-5">
            <p
              className="text-pretty text-[1.5rem] leading-[1.28] text-[var(--fg)] sm:text-[1.9rem]"
              style={{ fontFamily: "var(--font-display), serif" }}
            >
              The face stays private.
              <br />
              The work is the identity.
            </p>
            <div className="mt-10 space-y-0">
              {[
                ["Figures", "06 · one organization"],
                ["Palette", "Platinum monochrome"],
                ["Helmet", "Privacy, worn (STYLE_LAW §9)"],
                ["Source", "Generated in-canon · graded"],
              ].map(([k, v]) => (
                <div
                  key={k}
                  className="flex items-baseline justify-between border-t border-[var(--line)] py-3"
                >
                  <span className="label text-[var(--fg-faint)]">{k}</span>
                  <span className="label text-[var(--fg-mute)]" style={{ textTransform: "none" }}>
                    {v}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Row 2 — three plates, serif numerals over scrims */}
        <div className="mt-5 grid gap-5 sm:grid-cols-3">
          {[
            {
              src: "/generated/nodes/node-01.jpg",
              n: "02",
              role: "Solver",
              cap: "Builds and ships · does not critique",
            },
            {
              src: "/generated/nodes/node-04.jpg",
              n: "03",
              role: "Synthesizer",
              cap: "Signal condensed from noise",
            },
            {
              src: "/generated/nodes/node-06.jpg",
              n: "04",
              role: "Orchestrator",
              cap: "One directive · many hands",
            },
          ].map((f) => (
            <figure
              key={f.src}
              className="relative overflow-hidden rounded-[var(--radius)] border border-[var(--line)]"
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={f.src}
                alt={`The Nodes — ${f.role}. ${f.cap}. Mono fashion-editorial figure, generated in-canon.`}
                className="aspect-[4/5] w-full object-cover"
                loading="lazy"
              />
              <div
                aria-hidden
                className="pointer-events-none absolute inset-x-0 bottom-0 flex items-end justify-between bg-gradient-to-t from-black/90 via-black/40 to-transparent px-5 pb-4 pt-20"
              >
                <div>
                  <p className="label text-[var(--fg-dim)]">{f.role}</p>
                  <p className="mt-1 label text-[0.5rem] text-[var(--fg-faint)]">{f.cap}</p>
                </div>
                <span
                  className="metal-text text-[2.6rem] leading-none"
                  style={{ fontFamily: "var(--font-display), serif" }}
                >
                  {f.n}
                </span>
              </div>
            </figure>
          ))}
        </div>
      </Reveal>

      {/* ── Opening statement — full editorial weight ───────────────── */}
      <Reveal delay={80} className="mt-14 sm:mt-16">
        <div className="max-w-[48rem]">
          <blockquote className="relative pl-6 sm:pl-8">
            <span
              className="pointer-events-none absolute left-0 top-[-0.15em] font-serif text-[3rem] leading-none select-none"
              style={{ color: "var(--metal-4)" }}
              aria-hidden
            >
              &ldquo;
            </span>
            <p
              className="text-pretty leading-[1.84] sm:text-[1.15rem] lg:text-[1.22rem]"
              style={{ color: "var(--fg-dim)" }}
            >
              The aesthetic is not decoration. It is the argument: structure persists,
              and coherence made visible is the rarest material.
            </p>
          </blockquote>
        </div>
      </Reveal>

      {/* ── Divider Glyph — absolute symmetry, 1 = 1 ───────────────── */}
      <Reveal delay={160} className="mt-16 flex justify-center">
        <Glyph variant="divider" size={260} strokeOpacity={0.35} />
      </Reveal>

      {/* ── Studio Mission ────────────────────────────────────────── */}
      <Section
        title="AI-Native Film Studio"
        eyebrow="Studio · Emerging"
        className="mt-24 pt-12 sm:mt-32 sm:pt-16 lg:mt-36 lg:pt-20"
      >
        <div className="max-w-[50rem]">
          {/* Metadata rail — Abloh mono labels */}
          <div className="mb-10 grid grid-cols-2 gap-0 sm:grid-cols-4 border border-[var(--line)] rounded-[var(--radius)] overflow-hidden">
            {[
              { label: "Division", value: "Studio" },
              { label: "Status", value: "Emerging" },
              { label: "Channel", value: "@spektrelabs" },
              { label: "Metric", value: "σ = realized" },
            ].map((item, i) => (
              <Reveal
                key={item.label}
                delay={i * 60}
                className="border-r border-[var(--line)] last:border-r-0 px-5 py-4"
              >
                <p className="label text-[var(--fg-faint)] mb-1.5">{item.label}</p>
                <p
                  className="text-[0.92rem] tracking-[-0.01em]"
                  style={{ color: "var(--fg-dim)" }}
                >
                  {item.value}
                </p>
              </Reveal>
            ))}
          </div>

          <Reveal delay={100}>
            <div className="space-y-6" style={{ color: "var(--fg-dim)" }}>
              <p className="text-[1.02rem] leading-[1.84] sm:text-[1.1rem]">
                Studio is the production arm of Spektre Labs — where the invariants discovered
                in research become image, sequence, and world. AI-native from the ground up:
                generative models orchestrated as a director, not a filter.
              </p>
              <p className="text-[0.97rem] leading-[1.9]" style={{ color: "var(--fg-mute)" }}>
                The aesthetic is not lifted from genre convention. It is derived: Altered Carbon
                precision, Prada restraint, Fear of God negative space — rendered as a coherent
                visual language with a single invariant at its center. Symmetry is 1&nbsp;=&nbsp;1.
              </p>
            </div>
          </Reveal>

          {/* YouTube channel link — live status */}
          <Reveal delay={200} className="mt-10">
            <div className="flex items-center gap-5">
              <a
                href={LINKS.youtube}
                target="_blank"
                rel="noopener noreferrer"
                className="btn-metal rounded-[8px] px-5 py-2.5 text-[0.82rem] font-medium tracking-[0.06em] uppercase no-underline inline-block"
              >
                Watch on YouTube
              </a>
              <span className="h-px w-8" style={{ background: "var(--line-strong)" }} />
              <span className="label" style={{ color: "var(--signal)" }}>Live</span>
            </div>
          </Reveal>
        </div>
      </Section>

      {/* ── Media Reel Grid ──────────────────────────────────────────── */}
      <Section
        title="Media Reel"
        eyebrow="Production · Active"
        className="mt-32 pt-16 sm:mt-40 sm:pt-20 lg:mt-44 lg:pt-24"
      >
        <StudioFilms />

        <Reveal delay={100} className="mt-8">
          <p className="label" style={{ color: "var(--fg-faint)" }}>
            01 — Channel live on YouTube. 02–03 — Generative pipeline, in development.
            04–06 — Vision divisions, see below.
          </p>
        </Reveal>
      </Section>

      {/* ── Glyph seal — section break ──────────────────────────────── */}
      <Reveal delay={0} className="mt-28 flex flex-col items-center gap-6">
        <Glyph variant="seal" size={96} strokeOpacity={0.28} />
        <p className="label" style={{ color: "var(--fg-faint)" }}>
          Spektre Labs · Studio Division
        </p>
      </Reveal>

      {/* ── Vision: Games ────────────────────────────────────────────── */}
      <Section
        title="Games"
        eyebrow="Vision · In Development"
        className="mt-36 pt-16 sm:mt-44 sm:pt-20 lg:mt-52 lg:pt-24"
      >
        <div className="max-w-[50rem]">
          {/* Vision banner */}
          <Reveal delay={0}>
            <div
              className="mb-10 flex items-center gap-4 rounded-[8px] border px-5 py-3"
              style={{ borderColor: "var(--line)", background: "rgba(10,12,16,0.72)" }}
            >
              <span
                className="h-1.5 w-1.5 rounded-full shrink-0"
                style={{ background: "var(--fg-faint)" }}
              />
              <span className="label" style={{ color: "var(--fg-faint)" }}>
                In Development — honest trajectory, not shipped product
              </span>
            </div>
          </Reveal>

          <Reveal delay={80}>
            <div className="space-y-6">
              <p className="text-[1.1rem] leading-[1.82] text-balance font-semibold tracking-[-0.022em]" style={{ color: "var(--fg)" }}>
                AAA generative worlds. Structure as the engine.
              </p>
              <p className="text-[0.97rem] leading-[1.9]" style={{ color: "var(--fg-dim)" }}>
                The same invariants that govern system coherence in the research corpus
                apply to world design. A world holds together for the same reason a proof
                holds: internal consistency, no contradiction at the root. Games built from
                the Spektre Protocol are self-consistent by construction — not authored scene
                by scene, but derived from a set of structural axioms.
              </p>
              <p className="text-[0.93rem] leading-[1.9]" style={{ color: "var(--fg-mute)" }}>
                The aesthetic is canon: cold Atlantean geometry, platinum surface,
                OLED depth. Environments that feel excavated rather than constructed.
                Worlds that carry weight because their structure is real.
              </p>
            </div>
          </Reveal>

          {/* Domain tags — Abloh metadata grid */}
          <Reveal delay={160} className="mt-10">
            <div className="flex flex-wrap gap-0">
              {["Generative Worlds", "Structural Design", "AI World-Building", "Proc-Gen", "σ-Coherent Systems"].map((tag, i) => (
                <span
                  key={tag}
                  className="label mr-6 mb-4 text-[0.62rem] tracking-[0.2em]"
                  style={{ color: "var(--fg-faint)" }}
                >
                  {String(i + 1).padStart(2, "0")} — {tag}
                </span>
              ))}
            </div>
          </Reveal>
        </div>
      </Section>

      {/* ── Hairline divider ────────────────────────────────────────── */}
      <Reveal delay={0} className="mt-20 flex justify-center">
        <Glyph variant="divider" size={200} strokeOpacity={0.2} />
      </Reveal>

      {/* ── Vision: Shoreworld ───────────────────────────────────────── */}
      <Section
        title="Shoreworld"
        eyebrow="Vision · In Development"
        className="mt-36 pt-16 sm:mt-44 sm:pt-20 lg:mt-52 lg:pt-24"
      >
        <div className="max-w-[50rem]">
          {/* Vision banner */}
          <Reveal delay={0}>
            <div
              className="mb-10 flex items-center gap-4 rounded-[8px] border px-5 py-3"
              style={{ borderColor: "var(--line)", background: "rgba(10,12,16,0.72)" }}
            >
              <span
                className="h-1.5 w-1.5 rounded-full shrink-0"
                style={{ background: "var(--fg-faint)" }}
              />
              <span className="label" style={{ color: "var(--fg-faint)" }}>
                In Development — honest trajectory, not shipped product
              </span>
            </div>
          </Reveal>

          <Reveal delay={80}>
            <div className="space-y-6">
              <p className="text-[1.1rem] leading-[1.82] text-balance font-semibold tracking-[-0.022em]" style={{ color: "var(--fg)" }}>
                The world. The IP. The fiction at the center of everything.
              </p>
              <p className="text-[0.97rem] leading-[1.9]" style={{ color: "var(--fg-dim)" }}>
                Shoreworld is the narrative universe that contains the Spektre aesthetic —
                the place where the theory becomes mythology. A setting built from the same
                structural axioms as the research, expressed as story, image, and world.
                Cold. Precise. Ancient and post-human simultaneously.
              </p>
              <p className="text-[0.93rem] leading-[1.9]" style={{ color: "var(--fg-mute)" }}>
                The lore is the σ-axiom made narrative. Civilizations that held coherence
                and those that did not. Ruins that are not metaphors — they are proofs of
                collapse, made inhabitable. Shoreworld is not background; it is the argument
                the research has been building toward, given a body.
              </p>
            </div>
          </Reveal>

          {/* Domain tags */}
          <Reveal delay={160} className="mt-10">
            <div className="flex flex-wrap gap-0">
              {["World IP", "Dark-Luxury Sci-Fi", "Narrative Systems", "Franchise", "σ-Mythology"].map((tag, i) => (
                <span
                  key={tag}
                  className="label mr-6 mb-4 text-[0.62rem] tracking-[0.2em]"
                  style={{ color: "var(--fg-faint)" }}
                >
                  {String(i + 1).padStart(2, "0")} — {tag}
                </span>
              ))}
            </div>
          </Reveal>
        </div>
      </Section>

      {/* ── Linkage rail — cross-link to Research / Systems ─────────── */}
      <Section
        title="Connected Divisions"
        eyebrow="Linkages"
        className="mt-36 pt-16 sm:mt-44 sm:pt-20 lg:mt-48 lg:pt-20"
      >
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 max-w-[52rem]">
          {[
            {
              href: "/research",
              eyebrow: "Research",
              title: "Corpus + Protocol",
              desc: "The formal invariants — σ, K_crit, coherence — that underwrite every Studio artifact.",
              status: "Active",
            },
            {
              href: "/artifacts",
              eyebrow: "Systems",
              title: "σ-gate · open core",
              desc: "The runtime infrastructure: guardrail API and orchestration OS powering AI generation.",
              status: "Shipping",
            },
            {
              href: LINKS.youtube,
              eyebrow: "Channel",
              title: "@spektrelabs",
              desc: "Live on YouTube. First media artifacts of the Studio division.",
              status: "Live",
              external: true,
            },
          ].map((item, i) => (
            <Reveal key={item.title} delay={i * 80}>
              <a
                href={item.href}
                target={item.external ? "_blank" : undefined}
                rel={item.external ? "noopener noreferrer" : undefined}
                className="surface surface-hover group block rounded-[var(--radius)] p-6 sm:p-7 no-underline"
              >
                <p className="label mb-3" style={{ color: "var(--fg-faint)" }}>{item.eyebrow}</p>
                <h3
                  className="text-[1.05rem] font-semibold tracking-[-0.02em] leading-[1.2] mb-3"
                  style={{ color: "var(--fg)" }}
                >
                  {item.title}
                </h3>
                <p className="text-[0.87rem] leading-[1.82]" style={{ color: "var(--fg-mute)" }}>
                  {item.desc}
                </p>
                <div className="mt-5 flex items-center gap-3">
                  <span
                    className="h-px flex-1"
                    style={{ background: "var(--line)" }}
                  />
                  <span className="label text-[0.58rem]" style={{ color: item.status === "Live" ? "var(--signal)" : "var(--fg-faint)" }}>
                    {item.status}
                  </span>
                </div>
              </a>
            </Reveal>
          ))}
        </div>
      </Section>

      {/* ── Final seal — absolute symmetry ─────────────────────────── */}
      <Reveal delay={0} className="mt-40 mb-20 flex flex-col items-center gap-8 lg:mt-52">
        <Glyph variant="seal" size={140} strokeOpacity={0.32} />
        <div className="text-center">
          <p className="label mb-2" style={{ color: "var(--fg-faint)" }}>
            Spektre Labs · Studio Division
          </p>
          <p
            className="label text-[0.6rem] tracking-[0.26em]"
            style={{ color: "var(--fg-faint)", opacity: 0.6 }}
          >
            Research → Systems → Studio → Games → Shoreworld
          </p>
        </div>
      </Reveal>

      <div className="mt-20 lg:mt-28" />
    </div>
  );
}
